### ISSUE TITLE
Dead Links

### ISSUE THREAD

**Issue by Amourspirit** [flywire/lo-p#5]
Source: [Text API Overiew Section 6](https://github.com/flywire/lo-p/blob/main/docs/05-Text_API_Overview.md#6--using-and-comparing-text-cursors)

FreeTTS (https://freetts.sourceforge.net/): Dead Link

**Comment by flywire** [comment]
the original publication had many dead links that were kept for context when it was converted. They can be updated or removed as the text is revised.

A dead link checker is probably the most efficient way of identifying them and perhaps a script could color them red.
